### ISSUE TITLE
clicking on tag icon does not show posts with that tag

### ISSUE THREAD

**Issue by michaelaye** [danielfrg/middle-theme#1]
On your blog I went to the `Archives` link and then clicked on some tags, but none of them showed me the articles? I was redirected to an URL, here for the `computational-investing` tag:

http://danielfrg.com/tag/computational-investing.html

but Safari did just show a blank page. Is that a problem of Safari (OSX 10.10.4, v8.0.7) or of the blog theme?

**Comment by danielfrg** [comment]
Wow, I never tested that :D Just fixed it in https://github.com/danielfrg/middle-theme/commit/2dc4b047307d96c9ecd69865fdb8d6cafb1a2cba.

Thanks!
