### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by helgee** [danielfrg/middle-theme#2]
I really like your clean and beautiful Pelican theme, but I am not sure if I am allowed to use it since there is no license file in the repository.

What is your stance towards this?

**Comment by danielfrg** [comment]
Hi,

Sorry about that, I forgot to add a licence here since I had it on my blog repo and I was using this repo as a submodule.
I just added an Apache 2.0 License so you should be free to use this however you need :)

Thanks.

**Comment by helgee** [comment]
Excellent! Thanks a lot!
